
       <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <!-- <h2 class="section-heading text-uppercase">About</h2> -->
            <h3 class="section-subheading text-muted">ประวัติผู้พัฒนาเว็บไซต์</h3>
            <br><br/>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            <ul class="timeline">
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="img/about/2.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h3>นาย สุริยา  เขื่อนขัน</h3>
                    <h4 class="subheading">รหัสนักศึกษา 590610674</h4>
                  </div>
                </div>
              </li>
              <li class="timeline-inverted">
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="img/about/2.png" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h3>กำลังศีกษาอยู่ที่</h3>
                    <h4 class="subheading">มหาวิทยาลัยเชียงใหม่</h4>
                  </div>
                </div>
              </li>
              <li>
                <div class="timeline-image">
                  <img class="rounded-circle img-fluid" src="img/about/3.jpg" alt="">
                </div>
                <div class="timeline-panel">
                  <div class="timeline-heading">
                    <h3>คณะวิศวกรรมศาสตร์</h3>
                    <h3 class="subheading">สาขา วิศวกรรมศาสตร์คอมพิวเตอร์</h3>
                  </div>
                </div>
              </li>
              <li class="timeline-inverted">
                <div class="timeline-image">
                  <h4>Be Part
                    <br>Of Our
                    <br>Story!</h4>
                </div>
              </li>
            </ul>
          </div>
        </div>
      </div>

   